### ISSUE TITLE
Blank lines in code blocks within list items

### ISSUE THREAD

**Issue by adriangrigore** [karlb/smu#2]
For the following file:

```markdown
* a
  * b
        a

        b
```

`smu` renders:

```html
<ul>
<li><p>a
<ul>
<li>b
<pre><code>a
</code></pre>
</li>
</ul>
</p>
<pre><code>  b
</code></pre>
</li>
</ul>
```

and I would rather have it render something like:

```html
<ul>
<li>a
<ul>
<li>b
<pre><code>a

b
</code></pre>
</li>
</ul>
</li>
</ul>
```

Can I have it so `smu` respect blank lines in code block within lists? Any recommended way of solving this?

**Comment by karlb** [comment]
Sorry for the late reply. I didn't have notifications turned on for this repo, because notifications default to off for forks.

Since smu generally works on sections of the of the input, you can't just strip off the indentation at the start of the line and run the usual processing. Two approaches would be:
* Make a copy of the list item's content without the additional indentation and pass that to `process`. This would be inefficient and contrary to the usual smu approach.
* Pass on the information to ignore a certain amount of indentation to `process`. This is efficient but couples different concerns and makes the code more complicated.

I don't like either approach very much and don't see a better approach at the moment. If anyone has a good idea, please chime in. Otherwise I vote for just leaving this feature out.

**Comment by karlb** [comment]
I'm closing this issue, since I don't see a way to implement this with a good benefit/complexity ratio. If you see a good way to do it, feel free to send a PR and reopen.
